### PR TITLE
Fix lint

### PR DESCRIPTION
**Pull request by gwarf**
- Do not lint or check links on push, only do it in PRs
- Use the same list style everywhere
- build: fix containers names for AlmaLinux

### CODE REVIEW

**Comment by gwarf** [comment]
So it fails as expected 🎉 
See https://github.com/EGI-Federation/bdii-config-site/actions/runs/4406197836:
Screenshot 2023-03-13 at 15 52 03

**Review by enolfc — COMMENTED** [review]
Does it make sense to change here to Alma? Why not doing this in a separate PR?

**Comment by gwarf** [comment]
> Does it make sense to change here to Alma? Why not doing this in a separate PR?

Because I'm tired and already having issues with finding time for doing so many PR... So trying to save some time where I can

**Review by enolfc — APPROVED** [review]
👍

**Pull request merged**
